name: Publicar en Codeberg Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: docker
    steps:
      - name: Obtener el código
        uses: actions/checkout@v4
      - name: Instalar dependencias
        run: npm ci
      - name: Compilar sitio
        run: npm run build && mkdir _site && cp -r dist/. _site/
      - name: Publicar sitio
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: https://${{ forge.repository_owner }}.codeberg.page/${{ forge.repository_name }}/
          token: ${{ forge.token }}
          source: _site/
